export const nationalities: { code: string; nationality: string }[] = [
  { code: "AF", nationality: "Afghan" },
  { code: "AX", nationality: "Åland Island" },
  { code: "AL", nationality: "Albanian" },
  { code: "DZ", nationality: "Algerian" },
  { code: "US", nationality: "American" },
  { code: "UM", nationality: "American" },
  { code: "AS", nationality: "American Samoan" },
  { code: "AD", nationality: "Andorran" },
  { code: "AO", nationality: "Angolan" },
  { code: "AI", nationality: "Anguillan" },
  { code: "AQ", nationality: "Antarctic" },
  { code: "AG", nationality: "Antiguan or Barbudan" },
  { code: "AR", nationality: "Argentine" },
  { code: "AM", nationality: "Armenian" },
  { code: "AW", nationality: "Aruban" },
  { code: "AU", nationality: "Australian" },
  { code: "AT", nationality: "Austrian" },
  { code: "AZ", nationality: "Azerbaijani" },
  { code: "BS", nationality: "Bahamian" },
  { code: "BH", nationality: "Bahraini" },
  { code: "BD", nationality: "Bangladeshi" },
  { code: "BB", nationality: "Barbadian" },
  { code: "BY", nationality: "Belarusian" },
  { code: "BE", nationality: "Belgian" },
  { code: "BZ", nationality: "Belizean" },
  { code: "BJ", nationality: "Beninese" },
  { code: "BM", nationality: "Bermudian" },
  { code: "BT", nationality: "Bhutanese" },
  { code: "BO", nationality: "Bolivian" },
  { code: "BA", nationality: "Bosnian or Herzegovinian" },
  { code: "BW", nationality: "Botswana" },
  { code: "BV", nationality: "Bouvet Island" },
  { code: "BR", nationality: "Brazilian" },
  { code: "IO", nationality: "British Indian Ocean Territory" },
  { code: "VG", nationality: "British Virgin Island" },
  { code: "GB", nationality: "British" },
  { code: "BN", nationality: "Bruneian" },
  { code: "BG", nationality: "Bulgarian" },
  { code: "BF", nationality: "Burkinabe" },
  { code: "MM", nationality: "Burmese" },
  { code: "BI", nationality: "Burundian" },
  { code: "KH", nationality: "Cambodian" },
  { code: "CM", nationality: "Cameroonian" },
  { code: "CA", nationality: "Canadian" },
  { code: "CV", nationality: "Cape Verdean" },
  { code: "KY", nationality: "Caymanian" },
  { code: "CF", nationality: "Central African" },
  { code: "TD", nationality: "Chadian" },
  { code: "CL", nationality: "Chilean" },
  { code: "CN", nationality: "Chinese" },
  { code: "CX", nationality: "Christmas Island" },
  { code: "CC", nationality: "Cocos Island" },
  { code: "CO", nationality: "Colombian" },
  { code: "KM", nationality: "Comoran" },
  { code: "CG", nationality: "Congolese" },
  { code: "CD", nationality: "Congolese" },
  { code: "CK", nationality: "Cook Island" },
  { code: "CR", nationality: "Costa Rican" },
  { code: "HR", nationality: "Croatian" },
  { code: "CU", nationality: "Cuban" },
  { code: "CY", nationality: "Cypriot" },
  { code: "CZ", nationality: "Czech" },
  { code: "DK", nationality: "Danish" },
  { code: "DJ", nationality: "Djiboutian" },
  { code: "DM", nationality: "Dominican" },
  { code: "DO", nationality: "Dominican" },
  { code: "EC", nationality: "Ecuadorian" },
  { code: "EG", nationality: "Egyptian" },
  { code: "SV", nationality: "Salvadoran" },
  { code: "GQ", nationality: "Equatorial Guinean" },
  { code: "ER", nationality: "Eritrean" },
  { code: "EE", nationality: "Estonian" },
  { code: "ET", nationality: "Ethiopian" },
  { code: "FK", nationality: "Falkland Island" },
  { code: "FO", nationality: "Faroese" },
  { code: "FJ", nationality: "Fijian" },
  { code: "PH", nationality: "Filipino" },
  { code: "FI", nationality: "Finnish" },
  { code: "FR", nationality: "French" },
  { code: "GF", nationality: "French Guianese" },
  { code: "PF", nationality: "French Polynesian" },
  { code: "TF", nationality: "French Southern Territories" },
  { code: "GA", nationality: "Gabonese" },
  { code: "GM", nationality: "Gambian" },
  { code: "GE", nationality: "Georgian" },
  { code: "DE", nationality: "German" },
  { code: "GH", nationality: "Ghanaian" },
  { code: "GI", nationality: "Gibraltar" },
  { code: "GR", nationality: "Greek" },
  { code: "GL", nationality: "Greenlandic" },
  { code: "GD", nationality: "Grenadian" },
  { code: "GP", nationality: "Guadeloupe" },
  { code: "GU", nationality: "Guamanian" },
  { code: "GT", nationality: "Guatemalan" },
  { code: "GG", nationality: "Channel Island" },
  { code: "JE", nationality: "Channel Island" },
  { code: "GN", nationality: "Guinean" },
  { code: "GW", nationality: "Guinea-Bissauan" },
  { code: "GY", nationality: "Guyanese" },
  { code: "HT", nationality: "Haitian" },
  { code: "HM", nationality: "Heard Island or McDonald Islands" },
  { code: "HN", nationality: "Honduran" },
  { code: "HK", nationality: "Hong Kong" },
  { code: "HU", nationality: "Hungarian" },
  { code: "IS", nationality: "Icelandic" },
  { code: "IN", nationality: "Indian" },
  { code: "ID", nationality: "Indonesian" },
  { code: "IR", nationality: "Iranian" },
  { code: "IQ", nationality: "Iraqi" },
  { code: "IE", nationality: "Irish" },
  { code: "IM", nationality: "Manx" },
  { code: "IL", nationality: "Israeli" },
  { code: "IT", nationality: "Italian" },
  { code: "CI", nationality: "Ivorian" },
  { code: "JM", nationality: "Jamaican" },
  { code: "JP", nationality: "Japanese" },
  { code: "JO", nationality: "Jordanian" },
  { code: "KZ", nationality: "Kazakhstani" },
  { code: "KE", nationality: "Kenyan" },
  { code: "KI", nationality: "I-Kiribati" },
  { code: "KP", nationality: "North Korean" },
  { code: "KR", nationality: "South Korean" },
  { code: "KW", nationality: "Kuwaiti" },
  { code: "KG", nationality: "Kyrgyzstani" },
  { code: "LA", nationality: "Laotian" },
  { code: "LV", nationality: "Latvian" },
  { code: "LB", nationality: "Lebanese" },
  { code: "LS", nationality: "Mosotho" },
  { code: "LR", nationality: "Liberian" },
  { code: "LY", nationality: "Libyan" },
  { code: "LI", nationality: "Liechtenstein" },
  { code: "LT", nationality: "Lithuanian" },
  { code: "LU", nationality: "Luxembourg" },
  { code: "MO", nationality: "Macanese" },
  { code: "MK", nationality: "Macedonian" },
  { code: "MG", nationality: "Malagasy" },
  { code: "MW", nationality: "Malawian" },
  { code: "MY", nationality: "Malaysian" },
  { code: "MV", nationality: "Maldivian" },
  { code: "ML", nationality: "Malian" },
  { code: "MT", nationality: "Maltese" },
  { code: "MH", nationality: "Marshallese" },
  { code: "MQ", nationality: "Martiniquais" },
  { code: "MR", nationality: "Mauritanian" },
  { code: "MU", nationality: "Mauritian" },
  { code: "YT", nationality: "Mahoran" },
  { code: "MX", nationality: "Mexican" },
  { code: "FM", nationality: "Micronesian" },
  { code: "MD", nationality: "Moldovan" },
  { code: "MC", nationality: "Monegasque" },
  { code: "MN", nationality: "Mongolian" },
  { code: "MS", nationality: "Montserratian" },
  { code: "MA", nationality: "Moroccan" },
  { code: "MZ", nationality: "Mozambican" },
  { code: "MM", nationality: "Burmese" },
  { code: "NA", nationality: "Namibian" },
  { code: "NR", nationality: "Nauruan" },
  { code: "NP", nationality: "Nepali" },
  { code: "NL", nationality: "Dutch" },
  { code: "AN", nationality: "Dutch Antillean" },
  { code: "NC", nationality: "New Caledonian" },
  { code: "NZ", nationality: "New Zealand" },
  { code: "NI", nationality: "Nicaraguan" },
  { code: "NE", nationality: "Nigerien" },
  { code: "NG", nationality: "Nigerian" },
  { code: "NU", nationality: "Niuean" },
  { code: "NF", nationality: "Norfolk Island" },
  { code: "MP", nationality: "Northern Marianan" },
  { code: "NO", nationality: "Norwegian" },
  { code: "OM", nationality: "Omani" },
  { code: "PK", nationality: "Pakistani" },
  { code: "PW", nationality: "Palauan" },
  { code: "PS", nationality: "Palestinian" },
  { code: "PA", nationality: "Panamanian" },
  { code: "PG", nationality: "Papua New Guinean" },
  { code: "PY", nationality: "Paraguayan" },
  { code: "PE", nationality: "Peruvian" },
  { code: "PN", nationality: "Pitcairn Island" },
  { code: "PL", nationality: "Polish" },
  { code: "PT", nationality: "Portuguese" },
  { code: "PR", nationality: "Puerto Rican" },
  { code: "QA", nationality: "Qatari" },
  { code: "RE", nationality: "Reunionese" },
  { code: "RO", nationality: "Romanian" },
  { code: "RU", nationality: "Russian" },
  { code: "RW", nationality: "Rwandan" },
  { code: "SH", nationality: "Saint Helenian" },
  { code: "KN", nationality: "Kittitian or Nevisian" },
  { code: "LC", nationality: "Saint Lucian" },
  { code: "PM", nationality: "Saint-Pierrais or Miquelonnais" },
  { code: "VC", nationality: "Saint Vincentian" },
  { code: "WS", nationality: "Samoan" },
  { code: "SM", nationality: "Sammarinese" },
  { code: "ST", nationality: "Sao Tomean" },
  { code: "SA", nationality: "Saudi" },
  { code: "SN", nationality: "Senegalese" },
  { code: "CS", nationality: "Serbian or Montenegrin" },
  { code: "SC", nationality: "Seychellois" },
  { code: "SL", nationality: "Sierra Leonean" },
  { code: "SG", nationality: "Singaporean" },
  { code: "SK", nationality: "Slovak" },
  { code: "SI", nationality: "Slovenian" },
  { code: "SB", nationality: "Solomon Island" },
  { code: "SO", nationality: "Somali" },
  { code: "ZA", nationality: "South African" },
  { code: "GS", nationality: "South Georgia or South Sandwich Islands" },
  { code: "KR", nationality: "South Korean" },
  { code: "ES", nationality: "Spanish" },
  { code: "LK", nationality: "Sri Lankan" },
  { code: "SD", nationality: "Sudanese" },
  { code: "SR", nationality: "Surinamese" },
  { code: "SJ", nationality: "Svalbard" },
  { code: "SZ", nationality: "Swazi" },
  { code: "SE", nationality: "Swedish" },
  { code: "CH", nationality: "Swiss" },
  { code: "SY", nationality: "Syrian" },
  { code: "TW", nationality: "Taiwanese" },
  { code: "TJ", nationality: "Tajikistani" },
  { code: "TZ", nationality: "Tanzanian" },
  { code: "TH", nationality: "Thai" },
  { code: "TL", nationality: "Timorese" },
  { code: "TG", nationality: "Togolese" },
  { code: "TK", nationality: "Tokelauan" },
  { code: "TO", nationality: "Tongan" },
  { code: "TT", nationality: "Trinidadian or Tobagonian" },
  { code: "TN", nationality: "Tunisian" },
  { code: "TR", nationality: "Turkish" },
  { code: "TM", nationality: "Turkmen" },
  { code: "TC", nationality: "Turks and Caicos Island" },
  { code: "TV", nationality: "Tuvaluan" },
  { code: "UG", nationality: "Ugandan" },
  { code: "UA", nationality: "Ukrainian" },
  { code: "AE", nationality: "Emirati" },
  { code: "GB", nationality: "British" },
  { code: "US", nationality: "American" },
  { code: "UM", nationality: "American" },
  { code: "UY", nationality: "Uruguayan" },
  { code: "UZ", nationality: "Uzbekistani" },
  { code: "VU", nationality: "Vanuatuan" },
  { code: "VA", nationality: "Vatican" },
  { code: "VE", nationality: "Venezuelan" },
  { code: "VN", nationality: "Vietnamese" },
  { code: "VI", nationality: "U.S. Virgin Island" },
  { code: "WF", nationality: "Wallis and Futuna" },
  { code: "EH", nationality: "Sahrawi" },
  { code: "YE", nationality: "Yemeni" },
  { code: "ZM", nationality: "Zambian" },
  { code: "ZW", nationality: "Zimbabwean" }
];